#define MAX_RESERVATION_SIZE 256
#define STATE_ACCESS_DELAY_US 500000 // 500ms
#define MAX_JOB_FILE_NAME_SIZE 256
#define MAX_SESSION_COUNT 10
#define PIPE_NAME_SIZE 40
#define MAX_BUFFER_SIZE 256
#define MAX_MSG 5
#define EMS_SETUP_CODE '1'
#define EMS_QUIT_CODE '2'
#define EMS_CREATE_CODE '3'
#define EMS_RESERVE_CODE '4'
#define EMS_SHOW_CODE '5'
#define EMS_LIST_CODE '6'